export const Collections = {
    USER: 'user',
    OAUTHUSERS: 'oauthusers',
    CLIENT: 'clients',
    USERCLIENT: 'userclient',
    LOCATION: 'location',
    CATEGORY: 'category',
    BUSINESSLIST: 'businesslist',
    ROLES: 'roles',
    LOGSEARCH: 'logsearch',
    ENQUIRY: 'enquiry',
    STARTPROJECT: 'startproject',
    MESSAGE91: 'message91',
    MSGUSERS: 'msgusers',
    LOCATIONIP: 'locationip',
    PAYMENT: 'payment',
    ADVERTISMENTS: 'advertisments',
    SEODATAS: 'seodatas',
    SEOPAGECONTENT: 'seopagecontent',
    MRPDATAS: 'mrpdatas',
    ENQUIRYNOWDATAS: 'enquirynowdatas'
};

export const {
    USER,
    OAUTHUSERS,
    CLIENT,
    USERCLIENT,
    LOCATION,
    CATEGORY,
    BUSINESSLIST,
    ROLES,
    LOGSEARCH,
    ENQUIRY,
    STARTPROJECT,
    MESSAGE91,
    MSGUSERS,
    LOCATIONIP,
    PAYMENT,
    ADVERTISMENTS,
    SEODATAS,
    SEOPAGECONTENT,
    MRPDATAS,
    ENQUIRYNOWDATAS
} = Collections;