
//User

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILURE = "EDIT_USER_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

//Client
export const CREATE_USERCLIENT_REQUEST = "CREATE_USERCLIENT_REQUEST";
export const CREATE_USERCLIENT_SUCCESS = "CREATE_USERCLIENT_SUCCESS";
export const CREATE_USERCLIENT_FAILURE = "CREATE_USERCLIENT_FAILURE";

export const FETCH_USERSCLIENT_REQUEST = "FETCH_USERSCLIENT_REQUEST";
export const FETCH_USERSCLIENT_SUCCESS = "FETCH_USERSCLIENT_SUCCESS";
export const FETCH_USERSCLIENT_FAILURE = "FETCH_USERSCLIENT_FAILURE";

export const EDIT_USERCLIENT_REQUEST = "EDIT_USERCLIENT_REQUEST";
export const EDIT_USERCLIENT_SUCCESS = "EDIT_USERCLIENT_SUCCESS";
export const EDIT_USERCLIENT_FAILURE = "EDIT_USERCLIENT_FAILURE";

export const DELETE_USERCLIENT_REQUEST = "DELETE_USERCLIENT_REQUEST";
export const DELETE_USERCLIENT_SUCCESS = "DELETE_USERCLIENT_SUCCESS";
export const DELETE_USERCLIENT_FAILURE = "DELETE_USERCLIENT_FAILURE";

//Location
export const CREATE_LOCATION_REQUEST = "CREATE_LOCATION_REQUEST";
export const CREATE_LOCATION_SUCCESS = "CREATE_LOCATION_SUCCESS";
export const CREATE_LOCATION_FAILURE = "CREATE_LOCATION_FAILURE";

export const FETCH_LOCATION_REQUEST = "FETCH_LOCATION_REQUEST";
export const FETCH_LOCATION_SUCCESS = "FETCH_LOCATION_SUCCESS";
export const FETCH_LOCATION_FAILURE = "FETCH_LOCATION_FAILURE";

export const EDIT_LOCATION_REQUEST = "EDIT_LOCATION_REQUEST";
export const EDIT_LOCATION_SUCCESS = "EDIT_LOCATION_SUCCESS";
export const EDIT_LOCATION_FAILURE = "EDIT_LOCATION_FAILURE";

export const DELETE_LOCATION_REQUEST = "DELETE_LOCATION_REQUEST";
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
export const DELETE_LOCATION_FAILURE = "DELETE_LOCATION_FAILURE";

//CATEGORY
export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE";

export const EDIT_CATEGORY_REQUEST = "EDIT_CATEGORY_REQUEST";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";
export const EDIT_CATEGORY_FAILURE = "EDIT_CATEGORY_FAILURE";

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";

//BusinessList
export const CREATE_BUSINESS_REQUEST = "CREATE_BUSINESS_REQUEST";
export const CREATE_BUSINESS_SUCCESS = "CREATE_BUSINESS_SUCCESS";
export const CREATE_BUSINESS_FAILURE = "CREATE_BUSINESS_FAILURE";

export const FETCH_BUSINESS_REQUEST = "FETCH_BUSINESS_REQUEST";
export const FETCH_BUSINESS_SUCCESS = "FETCH_BUSINESS_SUCCESS";
export const FETCH_BUSINESS_FAILURE = "FETCH_BUSINESS_FAILURE";

export const EDIT_BUSINESS_REQUEST = "EDIT_BUSINESS_REQUEST";
export const EDIT_BUSINESS_SUCCESS = "EDIT_BUSINESS_SUCCESS";
export const EDIT_BUSINESS_FAILURE = "EDIT_BUSINESS_FAILURE";

export const DELETE_BUSINESS_REQUEST = "DELETE_BUSINESS_REQUEST";
export const DELETE_BUSINESS_SUCCESS = "DELETE_BUSINESS_SUCCESS";
export const DELETE_BUSINESS_FAILURE = "DELETE_BUSINESS_FAILURE";

export const ACTIVE_BUSINESS_REQUEST = "ACTIVE_BUSINESS_REQUEST";
export const ACTIVE_BUSINESS_SUCCESS = "ACTIVE_BUSINESS_SUCCESS";
export const ACTIVE_BUSINESS_FAILURE = "ACTIVE_BUSINESS_FAILURE";


export const FETCH_TRENDING_REQUEST = 'FETCH_TRENDING_REQUEST';
export const FETCH_TRENDING_SUCCESS = 'FETCH_TRENDING_SUCCESS';
export const FETCH_TRENDING_FAILURE = 'FETCH_TRENDING_FAILURE';

//Roles
export const CREATE_ROLES_REQUEST = "CREATE_ROLES_REQUEST";
export const CREATE_ROLES_SUCCESS = "CREATE_ROLES_SUCCESS";
export const CREATE_ROLES_FAILURE = "CREATE_ROLES_FAILURE";

export const FETCH_ROLES_REQUEST = "FETCH_ROLES_REQUEST";
export const FETCH_ROLES_SUCCESS = "FETCH_ROLES_SUCCESS";
export const FETCH_ROLES_FAILURE = "FETCH_ROLES_FAILURE";

export const EDIT_ROLES_REQUEST = "EDIT_ROLES_REQUEST";
export const EDIT_ROLES_SUCCESS = "EDIT_ROLES_SUCCESS";
export const EDIT_ROLES_FAILURE = "EDIT_ROLES_FAILURE";

export const DELETE_ROLES_REQUEST = "DELETE_ROLES_REQUEST";
export const DELETE_ROLES_SUCCESS = "DELETE_ROLES_SUCCESS";
export const DELETE_ROLES_FAILURE = "DELETE_ROLES_FAILURE";